apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb
  labels:
    app: influxdb
data:
  influxdb.conf: |
    [meta]
      dir="/var/lib/influxdb/meta"
    [data]
      dir="/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      trace-logging-enable=true
    [http]
      log-enabled=true
    [[graphite]]
      database="telegraf"
      user="telegraf"
      password="metricsmetricsmetricsmetrics"